### ISSUE TITLE
[P2] Implement Comprehensive Monitoring and Alerting for 10K Scale

### ISSUE THREAD

**Issue by nickna** [knnlabs/Conduit#180]
## Description
Set up monitoring, metrics, and alerting infrastructure to support 10,000 concurrent customers and ensure system health visibility at scale.

## Current State
- Basic health checks exist
- Limited metrics collection
- No centralized monitoring dashboard
- No automated alerting

## Monitoring Requirements
- Real-time metrics for all critical components
- Alerting for degraded performance
- Capacity planning metrics
- Customer experience monitoring
- Cost tracking and optimization

## Implementation Tasks
- [ ] Configure OpenTelemetry for distributed tracing
- [ ] Set up Prometheus metrics collection
- [ ] Create Grafana dashboards
- [ ] Implement custom health checks
- [ ] Configure alerting rules
- [ ] Add business metrics tracking
- [ ] Create runbooks for common alerts

### API Metrics
```csharp
// Response time by endpoint
_metrics.Measure.Timer.Time("api.request.duration", 
    new MetricTags("endpoint", endpoint, "method", method));

// Request rate
_metrics.Measure.Counter.Increment("api.requests.total",
    new MetricTags("endpoint", endpoint, "status", statusCode));

// Virtual key usage
_metrics.Measure.Counter.Increment("virtualkey.requests",
    new MetricTags("key_id", keyId, "model", model));

// Rate limit hits
_metrics.Measure.Counter.Increment("ratelimit.exceeded",
    new MetricTags("key_id", keyId));
```

### SignalR Metrics
```csharp
// Connection count
_metrics.Measure.Gauge.SetValue("signalr.connections.active", 
    activeConnectionCount);

// Message throughput
_metrics.Measure.Meter.Mark("signalr.messages.sent",
    new MetricTags("hub", hubName, "method", methodName));

// Connection duration
_metrics.Measure.Histogram.Update("signalr.connection.duration",
    connectionDurationSeconds);
```

### Task Processing Metrics
```csharp
// Task queue depth
_metrics.Measure.Gauge.SetValue("tasks.queue.depth",
    new MetricTags("task_type", taskType), queueDepth);

// Task processing time
_metrics.Measure.Timer.Time("task.processing.duration",
    new MetricTags("task_type", taskType, "provider", provider));

// Task success/failure rates
_metrics.Measure.Counter.Increment("task.completed",
    new MetricTags("task_type", taskType, "status", status));
```

### Infrastructure Metrics
```csharp
// Database connection pool
_metrics.Measure.Gauge.SetValue("database.connections.active", activeConnections);
_metrics.Measure.Gauge.SetValue("database.connections.available", availableConnections);

// Redis memory usage
_metrics.Measure.Gauge.SetValue("redis.memory.used", memoryUsedBytes);
_metrics.Measure.Gauge.SetValue("redis.keys.count", keyCount);

// RabbitMQ queue sizes
_metrics.Measure.Gauge.SetValue("rabbitmq.queue.messages", messageCount,
    new MetricTags("queue", queueName));
```

### 1. System Overview Dashboard
- Request rate and response times
- Error rate by service
- Active connections (SignalR, Database, Redis)
- Resource utilization (CPU, Memory, Network)

### 2. Customer Experience Dashboard
- API latency percentiles (p50, p95, p99)
- Task completion times by type
- Error rates by virtual key
- Rate limit violations

### 3. Task Processing Dashboard
- Queue depths by task type
- Processing times by provider
- Success/failure rates
- Webhook delivery stats

### 4. Infrastructure Dashboard
- Database connection pool usage
- Redis cache hit rates
- RabbitMQ throughput
- Service health status

### Critical Alerts (Page immediately)
```yaml
- name: API_DOWN
  expr: up{service="conduit-api"} == 0
  for: 1m
  
- name: DATABASE_CONNECTION_EXHAUSTED
  expr: database_connections_available < 10
  for: 2m
  
- name: HIGH_ERROR_RATE
  expr: rate(api_requests_total{status=~"5.."}[5m]) > 0.05
  for: 5m
```

### Warning Alerts (Notify on-call)
```yaml
- name: HIGH_RESPONSE_TIME
  expr: histogram_quantile(0.95, api_request_duration_seconds) > 1
  for: 10m
  
- name: QUEUE_BACKUP
  expr: tasks_queue_depth > 1000
  for: 5m
  
- name: SIGNALR_CONNECTION_LIMIT
  expr: signalr_connections_active > 8000
  for: 5m
```

### Info Alerts (Log for analysis)
```yaml
- name: CACHE_HIT_RATE_LOW
  expr: redis_cache_hit_rate < 0.8
  for: 15m
  
- name: WEBHOOK_DELIVERY_SLOW
  expr: webhook_delivery_duration_p95 > 5
  for: 10m
```

## OpenTelemetry Configuration
```csharp
builder.Services.AddOpenTelemetry()
    .WithTracing(tracerProviderBuilder =>
    {
        tracerProviderBuilder
            .AddAspNetCoreInstrumentation()
            .AddHttpClientInstrumentation()
            .AddSqlClientInstrumentation()
            .AddRedisInstrumentation()
            .AddMassTransitInstrumentation()
            .AddOtlpExporter(options =>
            {
                options.Endpoint = new Uri("http://otel-collector:4317");
            });
    })
    .WithMetrics(meterProviderBuilder =>
    {
        meterProviderBuilder
            .AddAspNetCoreInstrumentation()
            .AddRuntimeInstrumentation()
            .AddPrometheusExporter();
    });
```

## Custom Health Checks
```csharp
builder.Services.AddHealthChecks()
    .AddCheck<DatabaseConnectionHealthCheck>("database_connections")
    .AddCheck<RedisHealthCheck>("redis")
    .AddCheck<RabbitMQHealthCheck>("rabbitmq")
    .AddCheck<WebhookDeliveryHealthCheck>("webhook_delivery")
    .AddCheck<SignalRConnectionHealthCheck>("signalr_connections");
```

### High Response Time
1. Check current request rate
2. Verify database connection pool status
3. Check Redis cache hit rate
4. Review slow query logs
5. Scale horizontally if needed

### Queue Backup
1. Check consumer health
2. Verify RabbitMQ resources
3. Check for error loops
4. Scale consumers if needed
5. Enable circuit breakers

## Acceptance Criteria
- [ ] All critical metrics exposed via Prometheus
- [ ] Grafana dashboards deployed and accessible
- [ ] Alerts configured with proper thresholds
- [ ] Runbooks created for all critical alerts
- [ ] Distributed tracing working end-to-end
- [ ] Load test validates monitoring accuracy

## Dependencies
- Prometheus server
- Grafana instance
- OpenTelemetry collector
- Alert manager configuration

## References
- [OpenTelemetry .NET](https://opentelemetry.io/docs/instrumentation/net/)
- [Prometheus Best Practices](https://prometheus.io/docs/practices/)
- Epic: #172
